#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLySDD.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLSDD")]
	public partial class QLDDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertaccount(account instance);
    partial void Updateaccount(account instance);
    partial void Deleteaccount(account instance);
    partial void Insertdienke(dienke instance);
    partial void Updatedienke(dienke instance);
    partial void Deletedienke(dienke instance);
    partial void Insertcanho(canho instance);
    partial void Updatecanho(canho instance);
    partial void Deletecanho(canho instance);
    partial void Insertdsthanhtoan(dsthanhtoan instance);
    partial void Updatedsthanhtoan(dsthanhtoan instance);
    partial void Deletedsthanhtoan(dsthanhtoan instance);
    partial void Insertsudungdien(sudungdien instance);
    partial void Updatesudungdien(sudungdien instance);
    partial void Deletesudungdien(sudungdien instance);
    #endregion
		
		public QLDDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLSDDConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLDDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<account> accounts
		{
			get
			{
				return this.GetTable<account>();
			}
		}
		
		public System.Data.Linq.Table<dienke> dienkes
		{
			get
			{
				return this.GetTable<dienke>();
			}
		}
		
		public System.Data.Linq.Table<canho> canhos
		{
			get
			{
				return this.GetTable<canho>();
			}
		}
		
		public System.Data.Linq.Table<dsthanhtoan> dsthanhtoans
		{
			get
			{
				return this.GetTable<dsthanhtoan>();
			}
		}
		
		public System.Data.Linq.Table<sudungdien> sudungdiens
		{
			get
			{
				return this.GetTable<sudungdien>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.account")]
	public partial class account : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _username;
		
		private string _password;
		
		private string _canho;
		
		private string _role;
		
		private EntityRef<canho> _canho1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnusernameChanging(string value);
    partial void OnusernameChanged();
    partial void OnpasswordChanging(string value);
    partial void OnpasswordChanged();
    partial void OncanhoChanging(string value);
    partial void OncanhoChanged();
    partial void OnroleChanging(string value);
    partial void OnroleChanged();
    #endregion
		
		public account()
		{
			this._canho1 = default(EntityRef<canho>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_username", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string username
		{
			get
			{
				return this._username;
			}
			set
			{
				if ((this._username != value))
				{
					this.OnusernameChanging(value);
					this.SendPropertyChanging();
					this._username = value;
					this.SendPropertyChanged("username");
					this.OnusernameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_password", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string password
		{
			get
			{
				return this._password;
			}
			set
			{
				if ((this._password != value))
				{
					this.OnpasswordChanging(value);
					this.SendPropertyChanging();
					this._password = value;
					this.SendPropertyChanged("password");
					this.OnpasswordChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canho", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string canho
		{
			get
			{
				return this._canho;
			}
			set
			{
				if ((this._canho != value))
				{
					if (this._canho1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncanhoChanging(value);
					this.SendPropertyChanging();
					this._canho = value;
					this.SendPropertyChanged("canho");
					this.OncanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_role", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string role
		{
			get
			{
				return this._role;
			}
			set
			{
				if ((this._role != value))
				{
					this.OnroleChanging(value);
					this.SendPropertyChanging();
					this._role = value;
					this.SendPropertyChanged("role");
					this.OnroleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="canho_account", Storage="_canho1", ThisKey="canho", OtherKey="macanho", IsForeignKey=true)]
		public canho canho1
		{
			get
			{
				return this._canho1.Entity;
			}
			set
			{
				canho previousValue = this._canho1.Entity;
				if (((previousValue != value) 
							|| (this._canho1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._canho1.Entity = null;
						previousValue.accounts.Remove(this);
					}
					this._canho1.Entity = value;
					if ((value != null))
					{
						value.accounts.Add(this);
						this._canho = value.macanho;
					}
					else
					{
						this._canho = default(string);
					}
					this.SendPropertyChanged("canho1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dienke")]
	public partial class dienke : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _madienke;
		
		private string _thang;
		
		private string _nam;
		
		private double _giadien;
		
		private EntitySet<dsthanhtoan> _dsthanhtoans;
		
		private EntitySet<sudungdien> _sudungdiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmadienkeChanging(string value);
    partial void OnmadienkeChanged();
    partial void OnthangChanging(string value);
    partial void OnthangChanged();
    partial void OnnamChanging(string value);
    partial void OnnamChanged();
    partial void OngiadienChanging(double value);
    partial void OngiadienChanged();
    #endregion
		
		public dienke()
		{
			this._dsthanhtoans = new EntitySet<dsthanhtoan>(new Action<dsthanhtoan>(this.attach_dsthanhtoans), new Action<dsthanhtoan>(this.detach_dsthanhtoans));
			this._sudungdiens = new EntitySet<sudungdien>(new Action<sudungdien>(this.attach_sudungdiens), new Action<sudungdien>(this.detach_sudungdiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madienke", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madienke
		{
			get
			{
				return this._madienke;
			}
			set
			{
				if ((this._madienke != value))
				{
					this.OnmadienkeChanging(value);
					this.SendPropertyChanging();
					this._madienke = value;
					this.SendPropertyChanged("madienke");
					this.OnmadienkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_thang", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string thang
		{
			get
			{
				return this._thang;
			}
			set
			{
				if ((this._thang != value))
				{
					this.OnthangChanging(value);
					this.SendPropertyChanging();
					this._thang = value;
					this.SendPropertyChanged("thang");
					this.OnthangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nam", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string nam
		{
			get
			{
				return this._nam;
			}
			set
			{
				if ((this._nam != value))
				{
					this.OnnamChanging(value);
					this.SendPropertyChanging();
					this._nam = value;
					this.SendPropertyChanged("nam");
					this.OnnamChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_giadien", DbType="Float NOT NULL")]
		public double giadien
		{
			get
			{
				return this._giadien;
			}
			set
			{
				if ((this._giadien != value))
				{
					this.OngiadienChanging(value);
					this.SendPropertyChanging();
					this._giadien = value;
					this.SendPropertyChanged("giadien");
					this.OngiadienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dienke_dsthanhtoan", Storage="_dsthanhtoans", ThisKey="madienke", OtherKey="madienke")]
		public EntitySet<dsthanhtoan> dsthanhtoans
		{
			get
			{
				return this._dsthanhtoans;
			}
			set
			{
				this._dsthanhtoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dienke_sudungdien", Storage="_sudungdiens", ThisKey="madienke", OtherKey="madienke")]
		public EntitySet<sudungdien> sudungdiens
		{
			get
			{
				return this._sudungdiens;
			}
			set
			{
				this._sudungdiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_dsthanhtoans(dsthanhtoan entity)
		{
			this.SendPropertyChanging();
			entity.dienke = this;
		}
		
		private void detach_dsthanhtoans(dsthanhtoan entity)
		{
			this.SendPropertyChanging();
			entity.dienke = null;
		}
		
		private void attach_sudungdiens(sudungdien entity)
		{
			this.SendPropertyChanging();
			entity.dienke = this;
		}
		
		private void detach_sudungdiens(sudungdien entity)
		{
			this.SendPropertyChanging();
			entity.dienke = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.canho")]
	public partial class canho : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macanho;
		
		private string _tenchucanho;
		
		private string _gioitinh;
		
		private string _quequan;
		
		private string _sodienthoai;
		
		private string _email;
		
		private string _cccd;
		
		private EntitySet<account> _accounts;
		
		private EntitySet<dsthanhtoan> _dsthanhtoans;
		
		private EntitySet<sudungdien> _sudungdiens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacanhoChanging(string value);
    partial void OnmacanhoChanged();
    partial void OntenchucanhoChanging(string value);
    partial void OntenchucanhoChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnquequanChanging(string value);
    partial void OnquequanChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OncccdChanging(string value);
    partial void OncccdChanged();
    #endregion
		
		public canho()
		{
			this._accounts = new EntitySet<account>(new Action<account>(this.attach_accounts), new Action<account>(this.detach_accounts));
			this._dsthanhtoans = new EntitySet<dsthanhtoan>(new Action<dsthanhtoan>(this.attach_dsthanhtoans), new Action<dsthanhtoan>(this.detach_dsthanhtoans));
			this._sudungdiens = new EntitySet<sudungdien>(new Action<sudungdien>(this.attach_sudungdiens), new Action<sudungdien>(this.detach_sudungdiens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macanho", DbType="VarChar(5) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macanho
		{
			get
			{
				return this._macanho;
			}
			set
			{
				if ((this._macanho != value))
				{
					this.OnmacanhoChanging(value);
					this.SendPropertyChanging();
					this._macanho = value;
					this.SendPropertyChanged("macanho");
					this.OnmacanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenchucanho", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string tenchucanho
		{
			get
			{
				return this._tenchucanho;
			}
			set
			{
				if ((this._tenchucanho != value))
				{
					this.OntenchucanhoChanging(value);
					this.SendPropertyChanging();
					this._tenchucanho = value;
					this.SendPropertyChanged("tenchucanho");
					this.OntenchucanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quequan", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string quequan
		{
			get
			{
				return this._quequan;
			}
			set
			{
				if ((this._quequan != value))
				{
					this.OnquequanChanging(value);
					this.SendPropertyChanging();
					this._quequan = value;
					this.SendPropertyChanged("quequan");
					this.OnquequanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cccd", DbType="VarChar(12)")]
		public string cccd
		{
			get
			{
				return this._cccd;
			}
			set
			{
				if ((this._cccd != value))
				{
					this.OncccdChanging(value);
					this.SendPropertyChanging();
					this._cccd = value;
					this.SendPropertyChanged("cccd");
					this.OncccdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="canho_account", Storage="_accounts", ThisKey="macanho", OtherKey="canho")]
		public EntitySet<account> accounts
		{
			get
			{
				return this._accounts;
			}
			set
			{
				this._accounts.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="canho_dsthanhtoan", Storage="_dsthanhtoans", ThisKey="macanho", OtherKey="macanho")]
		public EntitySet<dsthanhtoan> dsthanhtoans
		{
			get
			{
				return this._dsthanhtoans;
			}
			set
			{
				this._dsthanhtoans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="canho_sudungdien", Storage="_sudungdiens", ThisKey="macanho", OtherKey="canho")]
		public EntitySet<sudungdien> sudungdiens
		{
			get
			{
				return this._sudungdiens;
			}
			set
			{
				this._sudungdiens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_accounts(account entity)
		{
			this.SendPropertyChanging();
			entity.canho1 = this;
		}
		
		private void detach_accounts(account entity)
		{
			this.SendPropertyChanging();
			entity.canho1 = null;
		}
		
		private void attach_dsthanhtoans(dsthanhtoan entity)
		{
			this.SendPropertyChanging();
			entity.canho = this;
		}
		
		private void detach_dsthanhtoans(dsthanhtoan entity)
		{
			this.SendPropertyChanging();
			entity.canho = null;
		}
		
		private void attach_sudungdiens(sudungdien entity)
		{
			this.SendPropertyChanging();
			entity.canho1 = this;
		}
		
		private void detach_sudungdiens(sudungdien entity)
		{
			this.SendPropertyChanging();
			entity.canho1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.dsthanhtoan")]
	public partial class dsthanhtoan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _mathanhtoan;
		
		private string _macanho;
		
		private string _madienke;
		
		private string _tinhtrang;
		
		private EntityRef<canho> _canho;
		
		private EntityRef<dienke> _dienke;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmathanhtoanChanging(int value);
    partial void OnmathanhtoanChanged();
    partial void OnmacanhoChanging(string value);
    partial void OnmacanhoChanged();
    partial void OnmadienkeChanging(string value);
    partial void OnmadienkeChanged();
    partial void OntinhtrangChanging(string value);
    partial void OntinhtrangChanged();
    #endregion
		
		public dsthanhtoan()
		{
			this._canho = default(EntityRef<canho>);
			this._dienke = default(EntityRef<dienke>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_mathanhtoan", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int mathanhtoan
		{
			get
			{
				return this._mathanhtoan;
			}
			set
			{
				if ((this._mathanhtoan != value))
				{
					this.OnmathanhtoanChanging(value);
					this.SendPropertyChanging();
					this._mathanhtoan = value;
					this.SendPropertyChanged("mathanhtoan");
					this.OnmathanhtoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macanho", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string macanho
		{
			get
			{
				return this._macanho;
			}
			set
			{
				if ((this._macanho != value))
				{
					if (this._canho.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacanhoChanging(value);
					this.SendPropertyChanging();
					this._macanho = value;
					this.SendPropertyChanged("macanho");
					this.OnmacanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madienke", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string madienke
		{
			get
			{
				return this._madienke;
			}
			set
			{
				if ((this._madienke != value))
				{
					if (this._dienke.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadienkeChanging(value);
					this.SendPropertyChanging();
					this._madienke = value;
					this.SendPropertyChanged("madienke");
					this.OnmadienkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tinhtrang", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string tinhtrang
		{
			get
			{
				return this._tinhtrang;
			}
			set
			{
				if ((this._tinhtrang != value))
				{
					this.OntinhtrangChanging(value);
					this.SendPropertyChanging();
					this._tinhtrang = value;
					this.SendPropertyChanged("tinhtrang");
					this.OntinhtrangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="canho_dsthanhtoan", Storage="_canho", ThisKey="macanho", OtherKey="macanho", IsForeignKey=true)]
		public canho canho
		{
			get
			{
				return this._canho.Entity;
			}
			set
			{
				canho previousValue = this._canho.Entity;
				if (((previousValue != value) 
							|| (this._canho.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._canho.Entity = null;
						previousValue.dsthanhtoans.Remove(this);
					}
					this._canho.Entity = value;
					if ((value != null))
					{
						value.dsthanhtoans.Add(this);
						this._macanho = value.macanho;
					}
					else
					{
						this._macanho = default(string);
					}
					this.SendPropertyChanged("canho");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dienke_dsthanhtoan", Storage="_dienke", ThisKey="madienke", OtherKey="madienke", IsForeignKey=true)]
		public dienke dienke
		{
			get
			{
				return this._dienke.Entity;
			}
			set
			{
				dienke previousValue = this._dienke.Entity;
				if (((previousValue != value) 
							|| (this._dienke.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dienke.Entity = null;
						previousValue.dsthanhtoans.Remove(this);
					}
					this._dienke.Entity = value;
					if ((value != null))
					{
						value.dsthanhtoans.Add(this);
						this._madienke = value.madienke;
					}
					else
					{
						this._madienke = default(string);
					}
					this.SendPropertyChanged("dienke");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sudungdien")]
	public partial class sudungdien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _masudung;
		
		private string _canho;
		
		private string _madienke;
		
		private double _soluongdien;
		
		private EntityRef<canho> _canho1;
		
		private EntityRef<dienke> _dienke;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmasudungChanging(int value);
    partial void OnmasudungChanged();
    partial void OncanhoChanging(string value);
    partial void OncanhoChanged();
    partial void OnmadienkeChanging(string value);
    partial void OnmadienkeChanged();
    partial void OnsoluongdienChanging(double value);
    partial void OnsoluongdienChanged();
    #endregion
		
		public sudungdien()
		{
			this._canho1 = default(EntityRef<canho>);
			this._dienke = default(EntityRef<dienke>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_masudung", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int masudung
		{
			get
			{
				return this._masudung;
			}
			set
			{
				if ((this._masudung != value))
				{
					this.OnmasudungChanging(value);
					this.SendPropertyChanging();
					this._masudung = value;
					this.SendPropertyChanged("masudung");
					this.OnmasudungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_canho", DbType="VarChar(5) NOT NULL", CanBeNull=false)]
		public string canho
		{
			get
			{
				return this._canho;
			}
			set
			{
				if ((this._canho != value))
				{
					if (this._canho1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OncanhoChanging(value);
					this.SendPropertyChanging();
					this._canho = value;
					this.SendPropertyChanged("canho");
					this.OncanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madienke", DbType="VarChar(10) NOT NULL", CanBeNull=false)]
		public string madienke
		{
			get
			{
				return this._madienke;
			}
			set
			{
				if ((this._madienke != value))
				{
					if (this._dienke.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadienkeChanging(value);
					this.SendPropertyChanging();
					this._madienke = value;
					this.SendPropertyChanged("madienke");
					this.OnmadienkeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_soluongdien", DbType="Float NOT NULL")]
		public double soluongdien
		{
			get
			{
				return this._soluongdien;
			}
			set
			{
				if ((this._soluongdien != value))
				{
					this.OnsoluongdienChanging(value);
					this.SendPropertyChanging();
					this._soluongdien = value;
					this.SendPropertyChanged("soluongdien");
					this.OnsoluongdienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="canho_sudungdien", Storage="_canho1", ThisKey="canho", OtherKey="macanho", IsForeignKey=true)]
		public canho canho1
		{
			get
			{
				return this._canho1.Entity;
			}
			set
			{
				canho previousValue = this._canho1.Entity;
				if (((previousValue != value) 
							|| (this._canho1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._canho1.Entity = null;
						previousValue.sudungdiens.Remove(this);
					}
					this._canho1.Entity = value;
					if ((value != null))
					{
						value.sudungdiens.Add(this);
						this._canho = value.macanho;
					}
					else
					{
						this._canho = default(string);
					}
					this.SendPropertyChanged("canho1");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="dienke_sudungdien", Storage="_dienke", ThisKey="madienke", OtherKey="madienke", IsForeignKey=true)]
		public dienke dienke
		{
			get
			{
				return this._dienke.Entity;
			}
			set
			{
				dienke previousValue = this._dienke.Entity;
				if (((previousValue != value) 
							|| (this._dienke.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._dienke.Entity = null;
						previousValue.sudungdiens.Remove(this);
					}
					this._dienke.Entity = value;
					if ((value != null))
					{
						value.sudungdiens.Add(this);
						this._madienke = value.madienke;
					}
					else
					{
						this._madienke = default(string);
					}
					this.SendPropertyChanged("dienke");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
